/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file should not be edited manually.
// It is generated by Next.js and committed here to keep typecheck stable on first install.
